### PR TITLE
Fix recovery mode, add after and before sync in webhook workflows and filter out inactive object

### PR DESCRIPTION
**Pull request by Berardpi**
@x4d3 Can you have a look?

@x4d3 @BrunoChauvet Not sure about the last one. What's the intended way for inactive object? Should we let each connector map inactive to the external api inactive field? what if it's not supported?

### CODE REVIEW

**Comment by BrunoChauvet** [comment]
Deletion should be local to applications. If the external application deletes a record, the preferred option is to flag the id_map as `inactive` and ignore subsequent updates unless the application reverts the deletion (if applicable).

**Comment by Berardpi** [comment]
Should we also set `status: 'INACTIVE'` in Connec! when the external application deletes a record?

**Comment by Berardpi** [comment]
Okay all done.
Records flagged as inactive in the external app are not pushed to or from connec!, but there's no propagation (deletion) of records flagged inactive in connec!

**Comment by x4d3** [comment]
LGTM.

**Pull request merged**
